main_app/__init__.py
from flask import Flask
from .home.routes import home



def create_app():
	app = Flask(__name__)
	# ------- Settings ---------- #
	app.config['SECRET_KEY'] = 'I am Yusee Programmer'

	app.register_blueprint(home)

	return app

main_app/home/routes.py
from flask import Blueprint, render_template, url_for, request, redirect, session

home = Blueprint('home',__name__)

# Change this variable to True/False every time you want to
# switch between index page with conference or without conference
there_is_pycon = True

@home.route('/')
@home.route('/home')
def home_page():
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if there_is_pycon:
		if session['lang'] == 'en':
			return render_template('index2.html')
		return render_template('index2-fr.html')

	if session['lang']=='en':
		return render_template('index.html')

	return render_template('index-fr.html')



# @home.route('/home2')
# def home2_page():
	
# 	return render_template('index2.html')


# ------About----------
@home.route('/about-pycon')
def about_pycon():
	title = "À propos de PyCon Niger"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		title = "About PyCon Niger"
		return render_template('about-pycon.html', title=title)
	return render_template('about-pycon-fr.html', title=title)


@home.route('/about-coc')
def about_coc():
	title = "Code of Conduct"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		return render_template('about-coc.html', title=title)
	return render_template('about-coc-fr.html', title=title)


@home.route('/about-health')
def about_health():
	title = "Directives de Santé et de Sécurité"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		title = "Health and Safety guidance"
		return render_template('about-health.html', title=title)
	return render_template('about-health-fr.html', title=title)

# --------End-About----------



# ----------If-There-is-PyCon-----------
@home.route('/sponsorship')
def sponsorship_page():
	title = "Sponsor"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		title = "Sponsor"
		return render_template('sponsorship.html', title=title)
	return render_template('sponsorship-fr.html', title=title)


@home.route('/speaking')
def speaking_page():
	title = "Devenez conférencier à PyCon Niger"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		title = "Speaking at PyCon Niger"
		return render_template('speaking.html', title=title)
	return render_template('speaking-fr.html', title=title)


@home.route('/attending')
def attending_page():
	title = "Assister à PyCon Niger"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		title = "Attend PyCon Niger"
		return render_template('attending.html', title=title)
	return render_template('attending-fr.html', title=title)


@home.route('/events')
def events_page():
	title = "Événements à PyCon Niger"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		title = "Events at PyCon Niger"
		return render_template('events.html', title=title)
	return render_template('events-fr.html', title=title)


@home.route('/schedule')
def schedule_page():
	title = "Programme des événements"
	if session.get('lang') == None:
		session['lang'] = 'fr'

	if session['lang'] == 'en':
		title = "Events Schedules"
		return render_template('schedule.html', title=title)
	return render_template('schedule-fr.html', title=title)

# ------------End-if-------------------



@home.route('/internationalize', methods=['GET', 'POST'])
def lang_btn():
	lang = request.args.get('lang')
	session['lang'] = lang
	return redirect(url_for('home.home_page'))



@home.route('/sampling')
def sampling_page():
	
	return render_template('sampling.html')

main_app/templates/about-health-fr.html
{% extends 'layout-fr.html' %}
{% block main %}
	<main>
        <!--? Hero Start -->
        <div class="slider-area2">
            <div class="slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap hero-cap2 text-center">
                                <h2>{{title}}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

		<section class="sample-text-area">
			<div class="container box_1170">
				<h1 style="font-weight: bolder;">Politique de Santé et de Sécurité de la Communauté Python Niger</h1>
				
				<p style="font-size: 20px; color: #432c16;">La santé et la sécurité de nos participants, du personnel et de la communauté sont nos priorités absolues. Les événements de la communauté Python Niger s'engagent à mettre en œuvre des mesures pour prévenir la propagation du COVID-19 et assurer un environnement sûr et sécurisé pour tous les participants. Cette politique décrit les directives et protocoles qui seront en place tout au long de l'événement.</p>

				<h2 style="padding-top: 25px; font-weight: bolder;">* Directives Générales *</h2>
				<h5>1. Exigence de Vaccination</h5>
				<p style="font-size: 20px; color: #432c16;">Tous les participants sont fortement encouragés à être entièrement vaccinés contre le COVID-19 avant de participer à l'événement. Une preuve de vaccination peut être exigée pour l'entrée.</p>

				<h5>2. Dépistages de Santé</h5>
				<p style="font-size: 20px; color: #432c16;">Les participants doivent effectuer des auto-évaluations de leur santé avant d'arriver à l'événement. Les personnes présentant des symptômes tels que de la fièvre, de la toux ou des difficultés respiratoires sont priées de rester chez elles.</p>

				<h5>3. Obligation de Porter un Masque</h5>
				<p style="font-size: 20px; color: #432c16;">Les masques doivent être portés en tout temps pendant l'événement, sauf lorsque vous mangez ou buvez activement. Les participants sont responsables d'apporter leurs propres masques, mais un approvisionnement limité sera disponible sur place.</p>

				<h5>4. Hygiène des Mains</h5>
				<p style="font-size: 20px; color: #432c16;">Des stations de désinfectant pour les mains seront placées dans tout le lieu. Les participants sont encouragés à se laver les mains fréquemment et à utiliser régulièrement du désinfectant pour les mains.</p>

				<h5>5. Distanciation Sociale</h5>
				<p style="font-size: 20px; color: #432c16;">Les participants doivent maintenir une distanciation physique conformément aux directives sanitaires locales. Les dispositions de sièges, les configurations des sessions et les espaces communs seront organisés pour faciliter la distanciation sociale.</p>

				<h5>6. Enregistrement Sans Contact</h5>
				<p style="font-size: 20px; color: #432c16;">Les participants sont encouragés à utiliser des méthodes sans contact pour les processus d'enregistrement et d'accueil. Des badges et des documents numériques seront fournis.</p>

				<h2 style="padding-top: 25px; font-weight: bolder;">* Mesures de Sécurité du Lieu *</h2>
				<h5>Ventilation</h5>
				<p style="font-size: 20px; color: #432c16;">Le lieu assurera une ventilation adéquate dans tous les espaces de l'événement. Dans la mesure du possible, des espaces extérieurs seront utilisés pour les activités.</p>

				<h5>1. Protocoles de Désinfection</h5>
				<p style="font-size: 20px; color: #432c16;">Des mesures de nettoyage et de désinfection renforcées seront mises en œuvre tout au long de l'événement, en mettant l'accent sur les surfaces fréquemment touchées et l'équipement partagé.</p>

				<h5>2. Premiers Secours et Assistance Médicale</h5>
				<p style="font-size: 20px; color: #432c16;">Du personnel médical formé sera disponible sur place pour fournir une assistance si nécessaire. Les stations de premiers secours seront clairement indiquées.</p>

				<h5>3. Procédures d'Évacuation d'Urgence</h5>
				<p style="font-size: 20px; color: #432c16;">Les participants seront informés des procédures d'évacuation d'urgence, et le personnel du lieu sera disponible pour aider en cas d'urgence.</p>

				<h2 style="padding-top: 25px; font-weight: bolder;">* Communication et Mises à Jour *</h2>
				<h5>1. Annonces de Santé et de Sécurité</h5>
				<p style="font-size: 20px; color: #432c16;">Des annonces régulières et des rappels sur les mesures de santé et de sécurité seront faits tout au long de l'événement.</p>

				<h5>2. Mises à Jour de l'Événement</h5>
				<p style="font-size: 20px; color: #432c16;">Les participants seront informés rapidement de tout changement dans le programme de l'événement ou des protocoles par le biais des canaux de communication officiels de l'événement.</p>

				<h5>3. Coopération des Participants</h5>
				<p style="font-size: 20px; color: #432c16;">Tous les participants sont tenus de coopérer avec les protocoles de santé et de sécurité pour garantir un environnement sûr et confortable pour tous.</p>

				<p style="font-size: 20px; color: #432c16;">En participant aux événements de la communauté Python Niger, les participants acceptent de se conformer à cette politique COVID/Santé & Sécurité. Les organisateurs se réservent le droit de mettre à jour et de modifier ces directives en fonction de l'évolution de la situation de santé publique.</p>

			</div>
		</section>

	</main>


{% endblock main %}

main_app/templates/about-health.html
{% extends 'layout.html' %}
{% block main %}
	<main>
        <!--? Hero Start -->
        <div class="slider-area2">
            <div class="slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap hero-cap2 text-center">
                                <h2>{{title}}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
		<section class="sample-text-area">
			<div class="container box_1170">
				<h1 style="font-weight: bolder;">Python Niger Community Health & Safety Policy</h1>
				
				<p style="font-size: 20px; color: #432c16;">The health and safety of our participants, staff, and community are our top priorities. The Python Niger Community events are committed to implementing measures to prevent the spread of COVID-19 and ensuring a safe and secure environment for all attendees. This policy outlines the guidelines and protocols that will be in place throughout the event.</p>

				<h2 style="padding-top: 25px; font-weight: bolder;">* General Guidelines *</h2>
				<h5>1. Vaccination Requirement</h5>
				<p style="font-size: 20px; color: #432c16;">All attendees are strongly encouraged to be fully vaccinated against COVID-19 before attending the event. Proof of vaccination may be required for entry.</p>

				<h5>2. Health Screenings</h5>
				<p style="font-size: 20px; color: #432c16;">Attendees are expected to conduct self-health assessments before arriving at the event. Individuals experiencing symptoms such as fever, cough, or difficulty breathing are requested to stay home.</p>

				<h5>3. Mask Mandate</h5>
				<p style="font-size: 20px; color: #432c16;">Masks must be worn at all times during the event, except when actively eating or drinking. Attendees are responsible for bringing their own masks, but a limited supply will be available at the venue.</p>

				<h5>4. Hand Hygiene</h5>
				<p style="font-size: 20px; color: #432c16;">Hand sanitizer stations will be placed throughout the venue. Attendees are encouraged to practice frequent handwashing and use hand sanitizer regularly.</p>

				<h5>5. Social Distancing</h5>
				<p style="font-size: 20px; color: #432c16;">Participants are required to maintain physical distancing in accordance with local health guidelines. Seating arrangements, session layouts, and common areas will be organized to facilitate social distancing.</p>

				<h5>6. Contactless Check-In</h5>
				<p style="font-size: 20px; color: #432c16;">Attendees are encouraged to use contactless methods for registration and check-in processes. Digital badges and materials will be provided.</p>

				<h2 style="padding-top: 25px; font-weight: bolder;">* Venue Safety Measures *</h2>
				<h5>Ventilation</h5>
				<p style="font-size: 20px; color: #432c16;">The venue will ensure adequate ventilation in all event spaces. Where possible, outdoor spaces will be utilized for activities.</p>

				<h5>1. Sanitization Protocols</h5>
				<p style="font-size: 20px; color: #432c16;">Enhanced cleaning and sanitization measures will be implemented throughout the event, with a focus on high-touch surfaces and shared equipment.</p>

				<h5>2. First Aid and Medical Assistance</h5>
				<p style="font-size: 20px; color: #432c16;">Trained medical personnel will be available on-site to provide assistance if needed. First aid stations will be clearly marked.</p>

				<h5>3. Emergency Evacuation Procedures</h5>
				<p style="font-size: 20px; color: #432c16;">Participants will be briefed on emergency evacuation procedures, and venue staff will be available to assist in case of an emergency.</p>

				<h2 style="padding-top: 25px; font-weight: bolder;">* Communication and Updates *</h2>
				<h5>1. Health and Safety Announcements</h5>
				<p style="font-size: 20px; color: #432c16;">Regular announcements and reminders about health and safety measures will be made throughout the event.</p>

				<h5>2. Event Updates</h5>
				<p style="font-size: 20px; color: #432c16;">Attendees will be informed promptly of any changes to the event schedule or protocols through official event communication channels.</p>

				<h5>3. Participant Cooperation</h5>
				<p style="font-size: 20px; color: #432c16;">All attendees are expected to cooperate with health and safety protocols to ensure a secure and comfortable environment for everyone.</p>

				<p style="font-size: 20px; color: #432c16;">By attending the Python Niger Community events, participants agree to comply with this COVID/Health & Safety Policy. The organizers reserve the right to update and modify these guidelines as needed based on the evolving public health situation.</p>

			</div>
		</section>

	</main>


{% endblock main %}

main_app/templates/about-pycon.html
{% extends 'layout.html' %}
{% block main %}
	<main>
        <!--? Hero Start -->
        <div class="slider-area2">
            <div class="slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap hero-cap2 text-center">
                                <h2>{{title}}</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
		<section class="sample-text-area">
			<div class="container box_1170">
				<h1 class="">What is PyCon Niger</h1>
				<p style="font-size: 20px; color: #432c16;">PyCon Niger is the premier annual international tech conference organized by Python Niger Community, bringing together Python enthusiasts, developers, and industry professionals from across Niger Republic. As the largest gathering of its kind in the country, PyCon Niger serves as a platform for collaboration, innovation, and knowledge-sharing within the Python community.</p>

				<p style="font-size: 20px; color: #432c16;">This event plays a crucial role in fostering the growth of the Python ecosystem in Niger by connecting individuals from various backgrounds who share a passion for Python programming. Through PyCon Niger, participants are empowered to explore the latest trends in Python programming, exchange ideas, and contribute to the advancement of technology in Niger Republic and beyond.</p>

				<p style="font-size: 20px; color: #432c16;">PyCon Niger also provides an excellent opportunity for attendees to network with like-minded professionals, learn from experts, and gain insights into emerging technologies. By bringing together a diverse group of participants, PyCon Niger helps to bridge the gap between academia and industry, ensuring that the skills being taught are relevant and in demand.</p>

				<p style="font-size: 20px; color: #432c16;">Ultimately, PyCon Niger is more than just a conference; it is a catalyst for technological advancement and innovation in the region. By fostering a strong community of Python developers and enthusiasts, PyCon Niger helps to drive progress and development, making a significant impact on the technological landscape of Niger Republic.</p>

			</div>
		</section>
	</main>


{% endblock main %}

main_app/templates/layout.html
<!doctype html>
<html class="no-js" lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> {{title}} </title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="../static/assets/img/favicon.ico">

 	<!-- CSS here -->
	<link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="../static/assets/css/owl.carousel.min.css">
	<link rel="stylesheet" href="../static/assets/css/slicknav.css">
	<link rel="stylesheet" href="../static/assets/css/animate.min.css">
	<link rel="stylesheet" href="../static/assets/css/magnific-popup.css">
	<link rel="stylesheet" href="../static/assets/css/fontawesome-all.min.css">
	<link rel="stylesheet" href="../static/assets/css/themify-icons.css">
	<link rel="stylesheet" href="../static/assets/css/slick.css">
	<link rel="stylesheet" href="../static/assets/css/nice-select.css">
	<link rel="stylesheet" href="../static/assets/css/style.css">
</head>
<body>
    <!--? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="../static/assets/img/logo/loder.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
	<header>
		<!--? Header Start -->
	    <div class="header-area">
	        <div class="main-header header-sticky">
	            <div class="container-fluid">
	                <div class="row align-items-center">
	                    <!-- Logo -->
	                    <div class="col-xl-2 col-lg-2 col-md-1">
	                        <div class="logo">
	                            <a href="{{ url_for('home.home_page') }}"><img src="../static/assets/img/logo/logo.png" alt=""></a>
	                        </div>
	                    </div>
	                    <div class="col-xl-10 col-lg-10 col-md-10">
	                        <div class="menu-main d-flex align-items-center justify-content-end">
	                            <!-- Main-menu -->
	                            <div class="main-menu f-right d-none d-lg-block">
	                                <nav>
	                                    <ul id="navigation">
	                                        <li><a href="{{ url_for('home.home_page') }}">Home</a></li>

	                                        <li><a href="#">About</a>
	                                            <ul class="submenu">
	                                                <li><a href="{{ url_for('home.about_pycon') }}">What is PyCon Niger</a></li>
	                                                <li><a href="https://pythonniger.org/coc">Code of Conduct</a></li>
	                                                <li><a href="{{ url_for('home.about_health') }}">Health and Safety Guidlines</a></li>
	                                            </ul>
	                                        </li>
	                                        
	                                        <li><a href="#">PyConNE2025</a>
	                                            <ul class="submenu">
	                                                <li><a href="{{ url_for('home.sponsorship_page') }}">Sponsorship</a></li>
                                                <li><a href="{{ url_for('home.speaking_page') }}">Speaking at PyConNE</a></li>
                                                <li><a href="{{ url_for('home.attending_page') }}">Attend PyCon Niger</a></li>
                                                <li><a href="{{ url_for('home.events_page') }}">Events</a></li>
                                                <li><a href="{{ url_for('home.schedule_page') }}">Schedules</a></li>
	                                            </ul>
	                                        </li>

	                                        <li><a href="#">Language 🇺🇸 | 🇫🇷</a>
	                                            <ul class="submenu">
	                                                <li><a href="{{ url_for('home.lang_btn', lang='en') }}">En 🇺🇸</a></li>
	                                                <li><a href="{{ url_for('home.lang_btn', lang='fr') }}">Fr 🇫🇷</a></li>
	                                            </ul>
	                                        </li>
	                                        
	                                        <!-- <li><a href="schedule.html">Speaking at PyConNE</a>
	                                            <ul class="submenu">
	                                                <li><a href="">Become a Speaker</a></li>
	                                                <li><a href="">Propose a Speaker</a></li>
	                                                <li><a href="">PyCon Niger 2024 Speakers</a></li>
	                                            </ul>
	                                        </li>
	                                        <li><a href="schedule.html">Attend PyCon Niger</a>
	                                            <ul class="submenu">
	                                                <li><a href="">PyCon Niger Online</a></li>
	                                                <li><a href="">Registration Informations</a></li>
	                                                <li><a href="">Travel Grants</a></li>
	                                                <li><a href="">Ticket Grants</a></li>
	                                                <li><a href="">Grants FAQ</a></li>
	                                            </ul>
	                                        </li>
	                                        <li><a href="schedule.html">Events</a>
	                                            <ul class="submenu">
	                                                <li><a href="">Conference Orientation</a></li>
	                                                <li><a href="">Keynote Addresses</a></li>
	                                                <li><a href="">Technical Workshops</a></li>
	                                                <li><a href="">Panel Discussions</a></li>
	                                                <li><a href="">Lightning Talks</a></li>
	                                                <li><a href="">Poster Sessions</a></li>
	                                                <li><a href="">Code Sprints</a></li>
	                                                <li><a href="">Birds of a Feather (BoF) Sessions</a></li>
	                                                <li><a href="">Career Fair</a></li>
	                                                <li><a href="">Hackathons</a></li>
	                                                <li><a href="">Community Building Activities</a></li>
	                                                <li><a href="">PyLadies Summit</a></li>
	                                                <li><a href="">Open Space</a></li>
	                                                <li><a href="">Beginners Mentorship</a></li>
	                                            </ul>
	                                        </li>
	                                        <li><a href="schedule.html">Schedules</a>
	                                            <ul class="submenu">
	                                                <li><a href="">Keynotes</a></li>
	                                                <li><a href="">Sponsors Presentations</a></li>
	                                                <li><a href="">Training</a></li>
	                                                <li><a href="">Posters</a></li>
	                                                <li><a href="">Talks</a></li>
	                                            </ul>
	                                        </li> -->
	                                        
	                                        <li><a href="https://pythonniger.org/contact">Contact</a></li>
	                                    </ul>
	                                </nav>
	                            </div>
	                        </div>
	                    </div>   
	                    <!-- Mobile Menu -->
	                    <div class="col-12">
	                        <div class="mobile_menu d-block d-lg-none"></div>
	                    </div>
	                </div>
	            </div>
	        </div>
	    </div>
	    <!-- Header End -->
	</header>

	{% block main %}
	{% endblock main %}

	<footer style="height: 20px;">

        <!-- footer-bottom area -->
        <div class="footer-bottom-area footer-bg">
            <div class="container">
                <div class="footer-border">
                     <div class="row d-flex justify-content-between align-items-center">
                         <div class="col-xl-10 col-lg-8 ">
                             <div class="footer-copy-right">
                                 <p><a href="https://pythonniger.org" target="_blank">Python Niger Community</a></p>
                             </div>
                         </div>
                         <div class="col-xl-2 col-lg-4">
                             <div class="footer-social f-right">
                                <a href="https://twitter.com/pythonniger"><i class="fab fa-twitter"></i></a>
                                <a href="https://www.facebook.com/pythonniger"><i class="fab fa-facebook-f"></i></a>
                             </div>
                         </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    
    <!-- Scroll Up -->
    <div id="back-top" style="background-color: #f15a24;">
        <a title="Go to Top" href="#"> <i class="fas fa-arrow-up"></i></a>
    </div>

	<!-- JS here -->

	<script src="../static/assets/js/vendor/modernizr-3.5.0.min.js"></script>
	<!-- Jquery, Popper, Bootstrap -->
	<script src="../static/assets/js/vendor/jquery-1.12.4.min.js"></script>
	<script src="../static/assets/js/popper.min.js"></script>
	<script src="../static/assets/js/bootstrap.min.js"></script>
	<!-- Jquery Mobile Menu -->
	<script src="../static/assets/js/jquery.slicknav.min.js"></script>

	<!-- Jquery Slick , Owl-Carousel Plugins -->
	<script src="../static/assets/js/owl.carousel.min.js"></script>
	<script src="../static/assets/js/slick.min.js"></script>
	<!-- One Page, Animated-HeadLin -->
	<script src="../static/assets/js/wow.min.js"></script>
	<script src="../static/assets/js/animated.headline.js"></script>
	<script src="../static/assets/js/jquery.magnific-popup.js"></script>
	
	<!-- Nice-select, sticky -->
	<script src="../static/assets/js/jquery.nice-select.min.js"></script>
	<script src="../static/assets/js/jquery.sticky.js"></script>
	
	<!-- contact js -->
	<script src="../static/assets/js/contact.js"></script>
	<script src="../static/assets/js/jquery.form.js"></script>
	<script src="../static/assets/js/jquery.validate.min.js"></script>
	<script src="../static/assets/js/mail-script.js"></script>
	<script src="../static/assets/js/jquery.ajaxchimp.min.js"></script>
	
	<!-- Jquery Plugins, main Jquery -->	
	<script src="../static/assets/js/plugins.js"></script>
	<script src="../static/assets/js/main.js"></script>
		
	</body>
</html>